### ISSUE TITLE
add CodePilot?

### ISSUE THREAD

**Issue by DimaVartanian** [supermarin/alcatraz-packages#137]
I know there were some issues with it before but they seem to be fixed from what I can tell:

https://github.com/macoscope/CodePilot

**Comment by julian-weinert** [comment]
Then make a clone of alcatraz-packages, add your Plugin to `packages.son` and make a pull request!

**Comment by justMaku** [comment]
Pull request created, now we wait :)

**Comment by jurre** [comment]
Thanks :)
