### ISSUE TITLE
XCProfileCleaner is not building

### ISSUE THREAD

**Issue by guillaume-algis** [supermarin/alcatraz-packages#340]
[An issue](https://github.com/lechium/ProvisioningProfileCleaner/issues/1) is filled in the plugin repo. 

Should we keep broken plugins in Alcatraz while waiting for a fix from the plugin maintainer, or remove the plugin until it's fixed?

**Comment by jurre** [comment]
Let's just rename the name in the package list, I'll push a fix in a bit
